MNT: convert 1-element array to scalar
For compatibility with `numpy >= 2.4.0`:
<https://numpy.org/doc/stable/release/2.4.0-notes.html#raise-typeerror-on-attempt-to-convert-array-with-ndim-0-to-scalar>

This change avoids the error:
TypeError: only 0-dimensional arrays can be converted to Python scalars