BUG: pass `int` values for `num` parameter of `numpy.linspace`
within the function `polytope.polytope.grid_region`,
by rounding up using function `math.ceil`. The function
`math.ceil` is used to obtain an `int` value
(`numpy.ceil` returns a non-integer type).

Previously, calling the function `grid_region` raised:

> TypeError: 'numpy.float64' object cannot be interpreted as an integer

Other changes:
- shift variable `density` to within `if` statement,
  because this variable is used only there
- use a `list` comprehension, instead of a `for` statement
- iterate over `zip`ped coordinates of bounding box endpoints,
  instead of using `numpy.hstack` and `numpy.ndarray.flatten`
  (simple is better than complex, PEP 20)
- use `range`, since Python 3 is now required
- pass parameter `num` to function `numpy.linspace` as keyword
  argument, instead of positionally
  (explicit is better than implicit, PEP 20).